#!/usr/bin/env bash
set -euo pipefail


# CONFIG...
# Input directory — contains all three SAF files
SAF_DIR="/media/birdlab/bird_hdd_13/Vibhav/tawny/07_pairwise_fst"

# Output directory — FST results go here
OUTDIR="/media/birdlab/bird_hdd_13/Vibhav/tawny/09_pairwise_fst"
mkdir -p "${OUTDIR}"
cd "${OUTDIR}"

THREADS=18 # GIVE AS PER YOUR MACHINE! 

# INPUTS — three SAF idx files
# Generated by 08a, 08b, 08c scripts
HYPER_SAF="${SAF_DIR}/hyperythra"
ALBO_SAF="${SAF_DIR}/albogularis"
ABU_SAF="${SAF_DIR}/abuensis"


# Verify all SAFs exist before starting
echo "Checking SAF files..."
for SAF in ${HYPER_SAF} ${ALBO_SAF} ${ABU_SAF}; do
  if [[ ! -f "${SAF}.saf.idx" ]]; then
    echo "ERROR: ${SAF}.saf.idx not found!"
    exit 1
  fi
  echo "  ${SAF}.saf.idx ✅"
done


# FUNCTION: pairwise FST
# whichFst 1 = Hudson/Bhatia estimator
#              recommended over Weir & Cockerham
#              for unequal sample sizes (7 vs 7 vs 4)
# fold 1     = folded SFS, required when using
#              reference as ancestral not true outgroup
# tole 1e-4  = loose tolerance, appropriate for 5x LC
#              likelihood surface noisy at low coverage
# per-site num/denom → R: sum(num)/sum(denom) per gene
# NOT mean of per-site FST — mean introduces bias!

run_pairwise_fst() {
  local SAF1=$1
  local SAF2=$2
  local OUT=$3

  echo "Pair: ${OUT}"
  echo "Started: $(date)"

  # 2D joint SFS
  realSFS \
    ${SAF1}.saf.idx \
    ${SAF2}.saf.idx \
    -fold 1 \
    -P ${THREADS} \
    -maxIter 100 \
    -tole 1e-4 \
    > ${OUT}.2dsfs \
    2> ${OUT}.convergence.log

  tail -3 ${OUT}.convergence.log

  # FST index — Bhatia/Hudson estimator
  realSFS fst index \
    ${SAF1}.saf.idx \
    ${SAF2}.saf.idx \
    -sfs ${OUT}.2dsfs \
    -whichFst 1 \
    -fstout ${OUT}

  # Global FST sanity check
  echo "--- Global FST: ${OUT} ---"
  realSFS fst stats ${OUT}.fst.idx

  # Per-site numerator + denominator for R
  # sum(num)/sum(denom) per gene = correct Bhatia FST
  # NOT mean of per-site values — mean introduces bias
  realSFS fst print \
    ${OUT}.fst.idx \
    > ${OUT}.per_site_fst.txt

  echo "${OUT} per-site lines: $(wc -l < ${OUT}.per_site_fst.txt)"
  echo "Done: ${OUT} at $(date)"
}


# Pairwise FST — 3 pairs
echo "Pairwise FST — Dumetia hyperythra subspecies"
echo "Started: $(date)"

run_pairwise_fst ${HYPER_SAF} ${ALBO_SAF} hyper_vs_albo
run_pairwise_fst ${HYPER_SAF} ${ABU_SAF}  hyper_vs_abu
run_pairwise_fst ${ALBO_SAF}  ${ABU_SAF}  albo_vs_abu

echo "DONE: $(date)"
echo ""
echo "Inputs from:  ${SAF_DIR}"
echo "Outputs in:   ${OUTDIR}"
echo ""
echo "Key outputs:"
echo "  hyper_vs_albo.per_site_fst.txt  <- per-site FST → R"
echo "  hyper_vs_abu.per_site_fst.txt   <- per-site FST → R"
echo "  albo_vs_abu.per_site_fst.txt    <- per-site FST → R"
echo "  *.2dsfs                         <- 2D joint SFS"
echo "  *.convergence.log               <- check convergence"

